nome = str(input("qua é seu nome:"))
idade = int(input("qual é sua idade:"))
altura = float(input("qual é sua altura:"))
print("seu nome é",nome)
print("sua idade é",idade)
print("sua altura é",altura)
print(type(nome))
print(type(idade))
print(type(altura))